//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FoodItems = newFoodItemsTable("public", "food_items", "")

type foodItemsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	Name      postgres.ColumnString
	Caption   postgres.ColumnString
	Rating    postgres.ColumnFloat
	PhotoPath postgres.ColumnString
	CreatedAt postgres.ColumnTimestamp
	UpdatedAt postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FoodItemsTable struct {
	foodItemsTable

	EXCLUDED foodItemsTable
}

// AS creates new FoodItemsTable with assigned alias
func (a FoodItemsTable) AS(alias string) *FoodItemsTable {
	return newFoodItemsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FoodItemsTable with assigned schema name
func (a FoodItemsTable) FromSchema(schemaName string) *FoodItemsTable {
	return newFoodItemsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FoodItemsTable with assigned table prefix
func (a FoodItemsTable) WithPrefix(prefix string) *FoodItemsTable {
	return newFoodItemsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FoodItemsTable with assigned table suffix
func (a FoodItemsTable) WithSuffix(suffix string) *FoodItemsTable {
	return newFoodItemsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFoodItemsTable(schemaName, tableName, alias string) *FoodItemsTable {
	return &FoodItemsTable{
		foodItemsTable: newFoodItemsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newFoodItemsTableImpl("", "excluded", ""),
	}
}

func newFoodItemsTableImpl(schemaName, tableName, alias string) foodItemsTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		NameColumn      = postgres.StringColumn("name")
		CaptionColumn   = postgres.StringColumn("caption")
		RatingColumn    = postgres.FloatColumn("rating")
		PhotoPathColumn = postgres.StringColumn("photo_path")
		CreatedAtColumn = postgres.TimestampColumn("created_at")
		UpdatedAtColumn = postgres.TimestampColumn("updated_at")
		allColumns      = postgres.ColumnList{IDColumn, NameColumn, CaptionColumn, RatingColumn, PhotoPathColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = postgres.ColumnList{NameColumn, CaptionColumn, RatingColumn, PhotoPathColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns  = postgres.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return foodItemsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Name:      NameColumn,
		Caption:   CaptionColumn,
		Rating:    RatingColumn,
		PhotoPath: PhotoPathColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
