// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: food.sql

package db

import (
	"context"
	"database/sql"
)

const createFoodItem = `-- name: CreateFoodItem :one
INSERT INTO food_items (name, caption, rating, photo_path) 
VALUES ($1, $2, $3, $4) 
RETURNING id, name, caption, rating, photo_path, created_at, updated_at
`

type CreateFoodItemParams struct {
	Name      string
	Caption   string
	Rating    sql.NullFloat64
	PhotoPath string
}

func (q *Queries) CreateFoodItem(ctx context.Context, arg CreateFoodItemParams) (FoodItem, error) {
	row := q.db.QueryRowContext(ctx, createFoodItem,
		arg.Name,
		arg.Caption,
		arg.Rating,
		arg.PhotoPath,
	)
	var i FoodItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Caption,
		&i.Rating,
		&i.PhotoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFoods = `-- name: ListFoods :many
select id, name, caption, rating, photo_path, created_at, updated_at from food_items
`

func (q *Queries) ListFoods(ctx context.Context) ([]FoodItem, error) {
	rows, err := q.db.QueryContext(ctx, listFoods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FoodItem
	for rows.Next() {
		var i FoodItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Caption,
			&i.Rating,
			&i.PhotoPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
