// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: food.sql

package db

import (
	"context"
)

const listFoods = `-- name: ListFoods :many
select id, name, caption, rating, photo_path, created_at, updated_at from food_items
`

func (q *Queries) ListFoods(ctx context.Context) ([]FoodItem, error) {
	rows, err := q.db.QueryContext(ctx, listFoods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FoodItem
	for rows.Next() {
		var i FoodItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Caption,
			&i.Rating,
			&i.PhotoPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
