// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type FoodItem struct {
	ID        int32
	Name      string
	Caption   string
	Rating    sql.NullFloat64
	PhotoPath string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
